apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ark-poc-api
  description: A simple backend service for the Ark POC frontend project.
  title: Ark POC API
  tags:
    - typescript
    - node
    - express
  annotations:
    github.com/project-slug: "thaboRach/ark-poc-api"
    backstage.io/kubernetes-id: ark-app
spec:
  type: service
  lifecycle: production
  owner: backend-team
  system: micro-services
  apiConsumedBy: ["ark-poc"]
